name: Watch for Power BI Desktop Updates

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  detect-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: microsoftdocs/powerbi-docs
          ref: main

      - name: Check for file change
        id: check
        run: |
          FILE="powerbi-docs/fundamentals/desktop-latest-update.md"
          HASH_FILE=".filehash"
          mkdir -p state
          if [ ! -f "state/$HASH_FILE" ]; then echo "" > "state/$HASH_FILE"; fi
          sha256sum $FILE > newhash
          if ! cmp -s newhash "state/$HASH_FILE"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Issue
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Power BI Desktop Updated!"
          content: |
            The Power BI Desktop update file has changed!

            [View commit history](https://github.com/MicrosoftDocs/powerbi-docs/commits/main/powerbi-docs/fundamentals/desktop-latest-update.md)

          labels: update
          assignees: ${{ github.actor }}

      - name: Save hash
        if: steps.check.outputs.changed == 'true'
        run: |
          mkdir -p state
          mv newhash state/.filehash
