name: Watch for File Change

on:
  schedule:
    - cron: '0 * * * *' # Check every hour
  workflow_dispatch:

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: microsoftdocs/powerbi-docs
          ref: main

      - name: Compare file hash
        id: check
        run: |
          curl -O https://raw.githubusercontent.com/<your-username>/powerbi-docs/main/.filehash
          sha256sum powerbi-docs/fundamentals/desktop-latest-update.md > newhash
          if ! cmp -s newhash .filehash; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Send Email
        if: steps.check.outputs.changed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yourprovider.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Power BI Desktop Updated!
          to: your-email@example.com
          from: GitHub Bot <your-email@example.com>
          body: The desktop-latest-update.md file has changed

      - name: Update hash
        if: steps.check.outputs.changed == 'true'
        run: |
          mv newhash .filehash
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .filehash
          git commit -m "Update file hash"
          git push
